token = '248756472:AAHcRGmbcjkk11H2R_hKMpLLE5DMU47TOEw'
sql_user = 'telegram_bot'
sql_passwd = '123456'
dbname = 'telegram'
table_name = 'test'
cols_names = ['id', 'user_id', 'user_name', 'message', 'date', 'to_me']
#father_id = '123990110'
father_id = '259114535'            # my id, actually, just for debug
bot_id = '248756472'
forwarded_table = 'forwarded'
messages_table = 'messages'
#forwarded_cols = ['id', 'from_id', 'first_name', 'last_name', 'username', 'date', 'text']
forwarded_cols = ['id', 'from_id', 'date', 'text']
#messages_cols = ['msg_id', 'from_id', 'first_name', 'last_name', 'username', 'date', 'reply_to_msg_id', 'forwarded_id', 'text', 'to_me']
messages_cols = ['msg_id', 'from_id', 'date', 'reply_to_msg_id', 'forwarded_id', 'text', 'to_me', 'unread']
reply_table = 'reply'                   # OK. When I'm forwarding a message to the father chat, I'm losing it's original id
reply_cols = ['father_id', 'source_id']   # "reply" table allows to restore this information
contacts_table = 'contacts'
contacts_cols = ['id', 'first_name', 'last_name', 'username']
blacklist_table = 'blacklist'
blacklist_cols = ['id', 'first_name', 'last_name', 'username']
